Work on nighly CI (WIP)

diff --git a/.github/workflows/nighly.yml b/.github/workflows/nighly.yml
--- a/.github/workflows/nighly.yml
+++ b/.github/workflows/nighly.yml
@@ -30,14 +30,20 @@ jobs:
         run: |
           set -eo pipefail
           .github/tools/nightly.ts
-          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.head_ref }}" != "${{ steps.choose.outputs.ref }}" ]]; then
-            echo "Pull request ref does not match the expected ref. Aborting."
-            exit 1
-          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: ${{ github.repository }}
-       
+      - name: Check pull request ref
+        if: github.event_name == 'pull_request'
+        run: |
+          set -eo pipefail
+          echo "Checking if the pull request ref matches the expected ref..."
+          echo "Expected ref: ${{ steps.choose.outputs.ref }}"
+          echo "Pull request ref: ${{ github.head_ref }}"
+          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.head_ref }}" != "${{ steps.choose.outputs.ref }}" ]]; then
+            echo "Pull request ref does not match the expected ref. Aborting."
+            exit 1
+          fi 
 
   build:
     needs: get-ref
